#ddev-generated
services:
  web:
    depends_on:
      redis:
        condition: service_healthy

  redis:
    container_name: ddev-${DDEV_SITENAME}-redis
    image: redis:7.4-alpine
    command: redis-server --appendonly yes --requirepass redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - "redis:/data"

volumes:
  redis:
    name: ddev-${DDEV_SITENAME}-redis
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}